config/routes.rb
Rails.application.routes.draw do

	# BG - the following two pages were automatically added to this file
	# when I ran rails generate controller Pages home about
	
  get 'pages/home'

  get 'pages/about'

  get 'pages/directions'

  resources :articles do
    # BG - make comments a NESTED RESOURCE with all the articles
    resources :comments
  end

  resources :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root 'users#index'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ActiveRecord::Base
  belongs_to :user
  has_many :comments


  validates :title, presence: true,
            length: { maximum: 50 }
  validates :post, presence: true
  validates :user_id, presence: true

end

app/models/bicycle.rb
class Bicycle
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :articles
  validates :password, presence: true,
            length: { minimum: 8 }
  validates :email, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  before_action :set_article, only: [:show, :edit, :update, :destroy]

  # GET /articles
  # GET /articles.json
  def index
    @articles = Article.all
  end

  # GET /articles/1
  # GET /articles/1.json
  def show
  end

  # GET /articles/new
  def new
    @article = Article.new
  end

  # GET /articles/1/edit
  def edit
  end

  # POST /articles
  # POST /articles.json
  def create
    @article = Article.new(article_params)

    respond_to do |format|
      if @article.save
        format.html { redirect_to @article, notice: 'Article was successfully created.' }
        format.json { render :show, status: :created, location: @article }
      else
        format.html { render :new }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /articles/1
  # PATCH/PUT /articles/1.json
  def update
    respond_to do |format|
      if @article.update(article_params)
        format.html { redirect_to @article, notice: 'Article was successfully updated.' }
        format.json { render :show, status: :ok, location: @article }
      else
        format.html { render :edit }
        format.json { render json: @article.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /articles/1
  # DELETE /articles/1.json
  def destroy
    @article.destroy
    respond_to do |format|
      format.html { redirect_to articles_url, notice: 'Article was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_article
      @article = Article.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def article_params
      params.require(:article).permit(:title, :post, :user_id)
    end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  # Whenever a new comment is created we need to handle it
  def create

    # Get Article comment is attached to
    @article = Article.find(params[:article_id])

    # Create and save comment
    @comment = @article.comments.create(comment_params)

    # Go to the article this comment is associated with
    # this is a redirect that will send the browser somewhere new - to_article_path
    # get the article the comment is associated with
    # create the comment and then redirect back to said article
    # and displaying the comments underneath that article
    #
    redirect_to article_path(@article)

  end


  # do not want anyone messing with comment_params - so we make this private
  # private methods always show up last in the file
  private
  def comment_params
    params.require(:comment).permit(:commenter, :body)
  end


end

app/controllers/pages_controller.rb
# BG - file was automatically created when I ran 
# rails generate controller Pages home about

# this created 2 different ACTIONS (methods) home and about
# also note that it create a directory named pages
# and created a controller for Pages

class PagesController < ApplicationController

  def home
  end

  def about
# BG ADD - this will not get to the page though
# render :text => 'Hello from PagesController - about'
  end

  def directions
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  # BG NOTE: before_action
  # Before a user is created we do not want to show edit, update or destroy
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

			def get_season()
    			# Object that retrieves date information
    			# Also retrieve year, day, wday (0 - 6), yday (0 - 365), 
    			# hour (24), min (59), sec (59), zone (Time Zone)
    			time = Time.new
 
    			if(time.month >= 3) && (time.month <= 5)
      				"Yeah it is Spring"
    			elsif (time.month > 5) && (time.month <= 8)
      				"Everyone Loves Summer"
    			elsif (time.month > 8) && (time.month <= 10)
      				"Put on Your Coat because Fall is here"
    			else
      				"Yuck Winter"
    			end
  			end
  			
  			# Gives max_value a default value of 10 if no attribute is passed
  			def get_random_number(max_value = 10)
    			rand(max_value)
  			end

		def get_random_welcome()
    		opening = ["What a beautiful day. ",
                "Welcome to our site. ",
                "Thank you for stopping by. "]
 
    		middle = ["We hope you find what you need. ",
                "We have a wide selection.  ",
                "Check out our sale items. "]
 
    		ending = ["Contact us if you need help. ",
                "We are here to server you. ",
                "Call us if you need to 412-555-1212. "]
 
    		"#{opening[rand(3)]} #{middle[rand(3)]}
    		#{ending[rand(3)]}"
 
  			end

 			def count_to_10
			x = 2
 
    		number_list = "1"
 
    		loop do
      			number_list = number_list + ", " + x.to_s
				x += 1
      			break if x > 10
    		end

    		# return the value to the view
			"#{number_list}"
			end  			

end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/articles/_form.html.erb
<%= form_for(article) do |f| %>
  <% if article.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(article.errors.count, "error") %> prohibited this article from being saved:</h2>

      <ul>
      <% article.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>

  <div class="field">
    <%= f.label :post %>
    <%= f.text_area :post %>
  </div>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.number_field :user_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/articles/edit.html.erb
<h1>Editing Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Show', @article %> |
<%= link_to 'Back', articles_path %>

app/views/articles/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Articles</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Post</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @articles.each do |article| %>

  <!-- BG - lets make odd and even rows display in different colors -->
      <tr class="<%= cycle('list_line_odd', 'list_line_even') %>">

        <td><%= article.title %></td>
        <td><%= article.post %></td>
        <td><%= article.user_id %></td>
        <td><%= link_to 'Show', article %></td>
        <td><%= link_to 'Edit', edit_article_path(article) %></td>
        <td><%= link_to 'Destroy', article, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Article', new_article_path %>

app/views/articles/new.html.erb
<h1>New Article</h1>

<%= render 'form', article: @article %>

<%= link_to 'Back', articles_path %>

app/views/articles/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @article.title %>
</p>

<p>
  <strong>Post:</strong>
  <%= @article.post %>
</p>

<p>
  <strong>User:</strong>
  <%= @article.user_id %>
</p>

<h2>Comments</h2>
<!-- BG - cycle through article.comments (nested resource)
<% @article.comments.each do |comment| %>

    <p>
      <strong>Commenter:</strong>
      <%= comment.commenter %>
    </p>

    <p>
      <strong>Comment:</strong>
      <%= comment.body %>
    </p>

  <% end %>


<h2>Add a comment:</h2>

<!-- BG - for THIS article Add commenst to it -->
<%= form_for([@article, @article.comments.build]) do |f| %>

  <!-- BG - now cycle through and generate the forms -->
  <!-- BG - add comments to the article -->

  <p>
    <%= f.label :commenter %><br>
    <%= f.text_field :commenter %>
  </p>

  <p>
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </p>

  <p>
    <%= f.submit %>
  </p>

<% end %>


<%= link_to 'Edit', edit_article_path(@article) %> |
<%= link_to 'Back', articles_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>

<head>

  <!-- static title -->
  <!-- title>Sampblog</title -->

  <!-- dynamic title - gets it from each page -->
  <title><%= yield(:title) %></title>

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>

  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

</head>

<body>

<div id="wrapper"> <!-- BEGIN WRAPPER -->

  <header>

    <%= link_to image_tag("USS_Enterprise_firing_phasers.jpg", :size =>'100x65',   alt: "USS_Enterprise"),
                {:controller => 'pages', :action => 'home'},
                {:class => 'websiteLogo'} %>

    <BR>

    <%= link_to 'READIT', {:controller => 'pages', :action => 'home'},
                {:class => 'websiteTitle'} %>

  </header>

  <nav id="horzNav">

    <p>
      <%= link_to 'Home', {:controller => 'pages', :action => 'home'} %>
      <%= link_to 'About', {:controller => 'pages', :action => 'about'} %>
      <%= link_to 'Directions', {:controller => 'pages', :action => 'directions'} %>
      <%= link_to 'Articles', {:controller => 'articles', :action => 'index'} %>
      <%= link_to 'Users', {:controller => 'users', :action => 'index'} %>
    </p>

  </nav>

  <main id="content">

  <!-- yeild - will output whatever is in the html of the pages -->
  <%= yield %>

  </main>

</div> <!-- END WRAPPER -->

</body>

</html>

app/views/pages/about.html.erb
<% provide(:title, "About Us") %>


	<h1>About Us</h1>
	<p>Find me in app/views/pages/about.html.erb</p>

	<!-- this does not work as it need to go in the <head> section -->
	  <!-- script>
	  function showAlert() { 
	    alert ("Hello World!");
	  }
	  </script -->

	<script>
	    alert ("Hello World!");
	</script>

	<script>
		var msg = "var msg - Hello World!"
	    alert (msg);
	</script>

	<p>We love what we do and do what we love.</p>
	<p>
	<a href="mailto:maxmcbyte@gmail.com?
	Subject=I%20need%20help">
	Contact Max for Help</a>
	</p>

app/views/pages/directions.html.erb
<% provide(:title, "Directions") %>

<h1>Directions</h1>
<p>Directions to our place</p>

app/views/pages/home.html.erb
<% provide(:title, "Welcome") %>

<p>Welcome to our home page</p>

				<!-- this is the function we created in app/helpers/application_helper.rb -->
				<p><%= get_season() %></p>
				<p><%= get_random_number(100) %></p>

				<p><%= get_random_welcome() %></p>

				<p><%= count_to_10() %></p>

				

app/views/users/_form.html.erb
<%= form_for(user) do |f| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :password %>
    <%= f.text_field :password %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<!-- this get the "partial" named _form.html.erb -->
<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>

<table>
  <thead>
    <tr>
      <th>Password</th>
      <th>Email</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>